# Generated by Django 5.1.3 on 2025-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=20)),
                ("doctor", models.CharField(max_length=100)),
                ("clinic", models.CharField(default="Down Town", max_length=100)),
            ],
            options={
                "db_table": "appointments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("HealthCareNumber", models.CharField(max_length=50, unique=True)),
                ("Clinic", models.CharField(max_length=100)),
                ("FirstName", models.CharField(max_length=50)),
                ("LastName", models.CharField(max_length=50)),
                ("DateOfBirth", models.DateField()),
                ("Email", models.EmailField(max_length=100, unique=True)),
                ("PhoneNumber", models.CharField(max_length=20, unique=True)),
                (
                    "Preference",
                    models.CharField(
                        choices=[("Email", "Email"), ("Phone", "Phone")],
                        default="Email",
                        max_length=5,
                    ),
                ),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
