# Generated by Django 5.1.3 on 2025-03-31 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="HealthCareNumber",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user",
                        to_field="HealthCareNumber",
                    ),
                ),
            ],
        ),
    ]
