# Generated by Django 5.1.3 on 2025-04-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_products"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="products",
            table="Products",
        ),
    ]
