# Generated by Django 5.1.3 on 2025-04-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                db_column="HealthCareNumber",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user",
            ),
        ),
    ]
