# Generated by Django 5.1.3 on 2025-04-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
