# Generated by Django 5.1.3 on 2025-04-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_cart_cartitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.AlterModelTable(
            name="cart",
            table="Cart",
        ),
    ]
