# Generated by Django 5.1.3 on 2025-04-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_invoice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"managed": False},
        ),
    ]
