# Generated by Django 5.1.3 on 2025-04-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_invoice_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="invoice",
            table="Invoice",
        ),
    ]
