# Generated by Django 5.1.3 on 2025-04-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_invoice_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="blogs/"),
                ),
                ("sub_text", models.TextField()),
                ("body", models.TextField()),
            ],
            options={
                "db_table": "Blogs",
                "managed": False,
            },
        ),
    ]
