# Generated by Django 5.1.3 on 2025-04-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_blog"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="blog",
            table="Blog",
        ),
    ]
