# Generated by Django 5.1.3 on 2025-04-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_blog_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("ssn", models.IntegerField(unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="doctors/"),
                ),
            ],
            options={
                "db_table": "doctors",
            },
        ),
    ]
